language: php

matrix:
  include:
    - php: 5.6
      env: deps=low
    - php: hhvm
      env: deps=low
    - php: 7.0
      env: deps=low
    - php: 5.6
    - php: hhvm
    - php: 7.0
  fast_finish: true
before-script:
    - mkdir build
    - mkdir build/logs

install:
  - composer self-update
  - if [ "$deps" = "no" ]; then composer --prefer-stable --no-interaction update; fi;
  - if [ "$deps" = "low" ]; then composer --prefer-lowest --prefer-stable --no-interaction update; fi;

env:
  global:
    - SYMFONY_DEPRECATIONS_HELPER=strict
    - deps=no
  
script:
  - ./vendor/bin/phpunit --disallow-test-output --report-useless-tests --coverage-clover ./build/logs/clover.xml
  - ./vendor/bin/phpunit --disallow-test-output --report-useless-tests --exclude-group=Coverage
  - ./vendor/bin/phpbench run --revs=1 --iterations=3 --warmup=1 --report=aggregate
  #- ./vendor/bin/phpcs --standard=PSR2 src/
  - ./vendor/bin/phpcpd src/
  #- ./vendor/bin/phpmd src text ruleset.xml

after_success:
  - travis_retry php vendor/bin/coveralls -v -x ./build/logs/clover.xml

cache:
  directories:
    - vendor

sudo: false
